# Generated by Django 4.2.1 on 2023-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=500)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="amount charged"
                    ),
                ),
                ("tokens", models.IntegerField(verbose_name="tokens generated")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
            ],
        ),
    ]
